// <auto-generated />
namespace EmployeeManagementTool.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedEmployeeTypeIdAndMakeItMandatory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedEmployeeTypeIdAndMakeItMandatory));
        
        string IMigrationMetadata.Id
        {
            get { return "202012291749476_AddedEmployeeTypeIdAndMakeItMandatory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
